### ISSUE TITLE
Android multicast issue (due to message-io?)

### ISSUE THREAD

**Issue by lemunozm** [sigmaSd/LanChat#1]
Hi @sigmaSd,

the multicast issue could be related to https://github.com/lemunozm/message-io/issues/70

I will notify you when I fix it :)

**Comment by sigmaSd** [comment]
Hello @lemunozm,

Thanks for looking into this issue!

I already explored this and I remember that I could reproduce it on my phone with a basic java multicast example.

I concluded that multicast is not really well supported on android, also I have an old phone and that might have  a big part in this.

Also I need to mention that I did not commit android folder, but for multicast to attempt to work you need to add this permission to the android manifest
```
<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
```

I'll give a try anyway after you figure out the message-io issue.

Thanks!

**Comment by lemunozm** [comment]
Thanks for the point @sigmaSd,

I already upload the fix to message-io. Version `0.14.2` contains it. I hope it is related and solves the android problem.

**Comment by sigmaSd** [comment]
Hello @lemunozm,

I updated to the latest message-io, unfortunately it doesn't fix the issue, like I said its very likely due to my old android phone, this is not something on message-io side.

**Comment by lemunozm** [comment]
Ok, thanks for testing it anyway :)
